# Project 5 — Your First Multi-Layer Neural Network (NumPy)

## Project Description

**Objective**: Build the forward pass of a simple Multi-Layer Perceptron from scratch using NumPy.

Requirements:

1. Create a network with:
   - 2 input features,
   - 3 hidden neurons,
   - 1 output neuron.
2. Initialize weights and biases manually (or randomly).
3. Implement:
   - matrix multiplication,
   - bias addition,
   - a nonlinear activation function (ReLU or sigmoid).
4. Perform a complete forward pass for several input samples.
5. Print the intermediate outputs of each layer so you can trace how information flows through the network.

Do not implement learning yet. The goal is to become comfortable with the architecture and the computations performed during forward propagation.

## My Solution

In [1]:
from pprint import pprint

import numpy as np
import numpy.typing as npt

In [42]:
class NeuralNetwork:
    def __print_on_verbose(self, text):
        if not self.verbose:
            return
        pprint(text)

    def __init__(self, n_neurons_per_layer: tuple[int, ...], verbose : bool = False):
        # I am numbering layers from 0
        self.n_neurons_per_layer = n_neurons_per_layer
        self.verbose = verbose

        self.n_layers = len(n_neurons_per_layer)

        self.__print_on_verbose(f"Initializing a Fully-Connected {len(n_neurons_per_layer)}-Layer Neural Network.")

        # Bias Augmented Weights per Layer starting from Layer 1 (First Hidden Layer)
        self.layer_weights = []
        rng = np.random.default_rng()

        for layer_number, n_neurons in enumerate(n_neurons_per_layer):
            if layer_number == 0:
                print("\n\n")
                self.__print_on_verbose(f"Input Layer (Layer {layer_number}): {n_neurons} Neuron(s).")
            elif layer_number == self.n_layers - 1:
                print("\n\n")
                self.__print_on_verbose(f"Ouput Layer (Layer {layer_number}): {n_neurons} Neuron(s).")
            else:
                print("\n\n")
                self.__print_on_verbose(f"Layer {layer_number}: {n_neurons} Neuron(s).")

            if layer_number == 0:
                self.layer_weights.append(None) # Just a placeholder
            else:
                w = rng.standard_normal((n_neurons, n_neurons_per_layer[layer_number - 1] + 1))
                self.layer_weights.append(w)
                self.__print_on_verbose("Weights (with Bias in Last Column):")
                self.__print_on_verbose(w)

        self.__print_on_verbose("Neural Network Initialized.")


    def predict_on_input(self, x : npt.NDArray[np.number]):
        if not isinstance(x, np.ndarray):
            raise TypeError(f"Expected np.ndarray, got {type(x).__name__}")
    
        if x.ndim != 2 or x.shape[0] != self.n_neurons_per_layer[0] or x.shape[1] != 1:
            raise ValueError(f"Expected shape ({self.n_neurons_per_layer[0]}, 1), but got shape {x.shape}")
        
        self.current_example = x

        self.__activate_layer(layer_number = self.n_layers - 1)

    def __leaky_relu_activation(self, x: np.ndarray, alpha: float = 0.01):
        return np.where(x > 0, x, alpha * x)

    def __sigmoid_activation(self, x: np.ndarray):
        return 1.0 / (1.0 + np.exp(-np.clip(x, -500, 500)))

    def __activate_layer(self, layer_number):
        if layer_number == 0:
            # Augment a row [1], corresponding to augmentation of Bias as last column is row weight
            return self.current_example

        W = self.layer_weights[layer_number]
        last_layer_activation = self.__activate_layer(layer_number - 1)


        weighted_sum = W @ np.vstack([last_layer_activation, np.array([1])])

        activation = self.__sigmoid_activation(weighted_sum) if layer_number == self.n_layers -1 else self.__leaky_relu_activation(weighted_sum)

        if layer_number == self.n_layers - 1:
            print("\n\n")
            self.__print_on_verbose("Output Layer")
        else:
            print("\n\n")
            self.__print_on_verbose(f"Layer {layer_number}")
        self.__print_on_verbose(f"W:")
        self.__print_on_verbose(W)
        self.__print_on_verbose("Activation of Last Layer")
        self.__print_on_verbose(last_layer_activation)
        self.__print_on_verbose("Weighted Sum of this Layer")
        self.__print_on_verbose(weighted_sum)
        self.__print_on_verbose("Activation of this Layer")
        self.__print_on_verbose(activation)

        
        return activation
            
        



In [43]:
my_first_neural_network = NeuralNetwork((2, 3, 1), verbose=True)

'Initializing a Fully-Connected 3-Layer Neural Network.'



'Input Layer (Layer 0): 2 Neuron(s).'



'Layer 1: 3 Neuron(s).'
'Weights (with Bias in Last Column):'
array([[-2.03222289, -0.62829516, -0.64450276],
       [ 0.19216336, -0.37653396, -0.27955423],
       [-1.01274137,  0.78755474, -0.56741489]])



'Ouput Layer (Layer 2): 1 Neuron(s).'
'Weights (with Bias in Last Column):'
array([[0.79723697, 0.15112509, 0.68625448, 1.21428602]])
'Neural Network Initialized.'


In [44]:
my_first_neural_network.predict_on_input(np.array([[4, -1]]).T)




'Layer 1'
'W:'
array([[-2.03222289, -0.62829516, -0.64450276],
       [ 0.19216336, -0.37653396, -0.27955423],
       [-1.01274137,  0.78755474, -0.56741489]])
'Activation of Last Layer'
array([[ 4],
       [-1]])
'Weighted Sum of this Layer'
array([[-8.14509918],
       [ 0.86563315],
       [-5.40593512]])
'Activation of this Layer'
array([[-0.08145099],
       [ 0.86563315],
       [-0.05405935]])



'Output Layer'
'W:'
array([[0.79723697, 0.15112509, 0.68625448, 1.21428602]])
'Activation of Last Layer'
array([[-0.08145099],
       [ 0.86563315],
       [-0.05405935]])
'Weighted Sum of this Layer'
array([[1.2430707]])
'Activation of this Layer'
array([[0.77609806]])


## What ChatGPT Expected Me to Learn from this Project

The goal was not training.

The goal was understanding the architecture.

You should now appreciate that:

- Every layer performs the same sequence of operations.
- Matrix multiplication replaces many individual neuron computations.
- Outputs from one layer become inputs to the next.
- A deep network is just repeated applications of a simple computational pattern.