# Project 12 — PyTorch Tensor Playground | PyTorch Fundamentals I — Tensors | The Language of Modern Deep Learning

## Project Description

**Objective**: Become comfortable creating and manipulating tensors in PyTorch.

Build a single Python script or Jupyter notebook that:

1. Demonstrates every tensor creation method covered in this chapter.
1. Prints tensor attributes (shape, dtype, device, ndim) for each example.
1. Performs indexing, slicing, reshaping, and broadcasting examples.
1. Compares element-wise multiplication with matrix multiplication.
1. Converts data between NumPy arrays and PyTorch tensors.
1. Detects whether CUDA is available and, if so, moves a tensor to the GPU and back to the CPU.

Document each section with short comments explaining what is happening and why it is useful.

## My Solution

### Helper Functions

In [1]:
def print_tensor_and_attributes(tensor, first_in_cell = False):
    if not first_in_cell:
        print("\n\n")
    print(f"Tensor:\n {tensor}\n")
    print(f"Number of Dimensions: {tensor.ndim}")
    print(f"Shape: {tensor.shape}")
    print(f"Datatype: {tensor.dtype}")
    print(f"Current Device: {tensor.device}")

If NumPy is the language of scientific computing, PyTorch is the language of deep learning.

So far, every equation we've written has involved vectors and matrices.

For example,

$$z=Wx+b$$

On paper, these are mathematical objects.

Inside a computer, they must be represented as data structures.

In NumPy, we use **ndarray**s.

In PyTorch, we use **tensor**s.

### What is PyTorch

PyTorch is an open-source deep learning framework developed originally by Facebook AI Research (FAIR).

It provides:

- Tensor computation (similar to NumPy),
- Automatic differentiation (Autograd),
- GPU acceleration,
- Neural network modules,
- Optimizers,
- Data loading utilities,
- A large ecosystem for research and production.

We can think of **PyTorch** as:

> NumPy + automatic differentiation + GPU support + deep learning tools.

### What is a Tensor?

A tensor is PyTorch's fundamental data structure.

Mathematically:
- Scalar → 0-dimensional tensor
- Vector → 1-dimensional tensor
- Matrix → 2-dimensional tensor
- Higher-dimensional arrays → higher-order tensors

Examples:

$5$ is a scalar.

$[1,2,3]$ is a vector.

$\bigl[ \begin{smallmatrix} 1 & 2 \\ 3& 4 \end{smallmatrix} \bigr]$ is a matrix.

All of these are tensors.

### Creating PyTorch Tensors

In [2]:
import torch

a = torch.tensor(5)

b = torch.tensor([1, 2, 3])

c = torch.tensor([[1, 2],
                  [3, 4]])

In [3]:
print_tensor_and_attributes(a, first_in_cell=True)
print_tensor_and_attributes(b)
print_tensor_and_attributes(c)

Tensor:
 5

Number of Dimensions: 0
Shape: torch.Size([])
Datatype: torch.int64
Current Device: cpu



Tensor:
 tensor([1, 2, 3])

Number of Dimensions: 1
Shape: torch.Size([3])
Datatype: torch.int64
Current Device: cpu



Tensor:
 tensor([[1, 2],
        [3, 4]])

Number of Dimensions: 2
Shape: torch.Size([2, 2])
Datatype: torch.int64
Current Device: cpu


Unlike NumPy, tensors can participate directly in automatic differentiation.

### Tensor Attributes

In [4]:
x = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])

In [5]:
x.shape

torch.Size([2, 3])

In [6]:
x.size()

torch.Size([2, 3])

In [7]:
x.ndim

2

In [8]:
x.dtype

torch.int64

In [9]:
# indicates where the tensor resides: CPU, GPU (CUDA, if available)
x.device

device(type='cpu')

### Tensor Data Types

| Type            | Description                 |
| --------------- | --------------------------- |
| `torch.float32` | Default floating-point type |
| `torch.float64` | Double precision            |
| `torch.int64`   | Integer                     |
| `torch.bool`    | Boolean                     |

Deep learning models typically use `float32` because it offers a good balance between precision and computational efficiency.

### Creating Special Tensors

A 3×4 tensor of zeros.

In [14]:
zero_tensor = torch.zeros(3, 4)

In [12]:
print_tensor_and_attributes(zero_tensor, first_in_cell=True)

Tensor:
 tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

Number of Dimensions: 2
Shape: torch.Size([3, 4])
Datatype: torch.float32
Current Device: cpu


A tensor filled with ones.

In [15]:
ones_tensor = torch.ones(2, 5)

In [17]:
print_tensor_and_attributes(ones_tensor, first_in_cell=True)

Tensor:
 tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

Number of Dimensions: 2
Shape: torch.Size([2, 5])
Datatype: torch.float32
Current Device: cpu


A 4×4 identity matrix.

In [18]:
identity_tensor = torch.eye(4)

In [19]:
print_tensor_and_attributes(identity_tensor, first_in_cell=True)

Tensor:
 tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

Number of Dimensions: 2
Shape: torch.Size([4, 4])
Datatype: torch.float32
Current Device: cpu


To create `tensor([0,1,2,...,9])`

In [20]:
consecutive_int_tensor = torch.arange(0, 10)

In [21]:
print_tensor_and_attributes(consecutive_int_tensor, first_in_cell=True)

Tensor:
 tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Number of Dimensions: 1
Shape: torch.Size([10])
Datatype: torch.int64
Current Device: cpu


To create a 1D Tensor of five equally spaced values between 0 and 1.

In [22]:
evenly_spaced_int_tensor = torch.linspace(0, 1, 5)

In [23]:
print_tensor_and_attributes(evenly_spaced_int_tensor, first_in_cell=True)

Tensor:
 tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])

Number of Dimensions: 1
Shape: torch.Size([5])
Datatype: torch.float32
Current Device: cpu


### Creating Random Tensors

Random initialization is essential because neural network weights are usually initialized randomly.

Sampling from Uniform distribution over [0,1)

In [25]:
tensor = torch.rand(3, 2)

print_tensor_and_attributes(tensor, first_in_cell=True)

Tensor:
 tensor([[0.5299, 0.1593],
        [0.5968, 0.7757],
        [0.7812, 0.9347]])

Number of Dimensions: 2
Shape: torch.Size([3, 2])
Datatype: torch.float32
Current Device: cpu


Sampling from Standard Normal Distribution

In [26]:
tensor = torch.randn(3, 2)

print_tensor_and_attributes(tensor, first_in_cell=True)

Tensor:
 tensor([[-0.8420,  0.0521],
        [ 0.6593, -0.3994],
        [-1.0791,  0.3740]])

Number of Dimensions: 2
Shape: torch.Size([3, 2])
Datatype: torch.float32
Current Device: cpu


Tensor of Random integers from 0 to 9.

In [27]:
tensor = torch.randint(0, 10, (2, 3))

print_tensor_and_attributes(tensor, first_in_cell=True)

Tensor:
 tensor([[9, 9, 2],
        [3, 5, 7]])

Number of Dimensions: 2
Shape: torch.Size([2, 3])
Datatype: torch.int64
Current Device: cpu


### Reproducibility

Machine learning experiments should be reproducible.

Set a random seed:

In [23]:
torch.manual_seed(42)

Using the same seed ensures that random tensor generation is repeatable on the same hardware and software configuration.

### Tensor Shapes

In [24]:
torch.tensor(5).shape

torch.Size([])

In [25]:
torch.tensor([1,2,3]).shape

torch.Size([3])

In [26]:
torch.tensor([[1,2,3],
              [4,5,6]]).shape

torch.Size([2, 3])

Always verify tensor shapes when debugging models.

### Indexing and Slicing

In [36]:
# First Row

x[0]

tensor([1, 2, 3])

In [33]:
# 2nd Column

x[:,1]

tensor([2, 5])

In [29]:
# Element is 2nd Row and 3rd Column

x[1,2]

tensor(6)

In [30]:
# All rows, columns from index 1 onward.

x[:,1:]

tensor([[2, 3],
        [5, 6]])

### Reshaping Tensors

In [40]:
x = torch.arange(12)
assert x.shape == torch.Size([12])

y = x.reshape(3, 4)

In [39]:
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [41]:
y

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [42]:
x.reshape(2, 3, 2)

tensor([[[ 0,  1],
         [ 2,  3],
         [ 4,  5]],

        [[ 6,  7],
         [ 8,  9],
         [10, 11]]])

Historically, `torch.view()` was commonly used for reshaping contiguous tensors. Today, `tensor.reshape()` is often preferred because it can handle both contiguous and non-contiguous tensors by creating a copy when necessary.

### Tensor Arithmetic

**Vectorized and Element-Wise**

- `a + b`
- `a - b`
- `a * b`

**Matrix Multiplication**
- `a @ b`, or equivalently, `torch.matmul(a, b)`

In [31]:
tensor_a = torch.tensor([[1, 2], [3, 4]])

tensor_b = torch.tensor([[5, 6], [7, 8]])

# Element-Wise Multiplication
print("Element-Wise Product:")
print(tensor_a * tensor_b)

# Matrix Product
print("Matrix Product:")
print(tensor_a @ tensor_b)

Element-Wise Product:
tensor([[ 5, 12],
        [21, 32]])
Matrix Product:
tensor([[19, 22],
        [43, 50]])


### Broadcasting

Broadcasting allows tensors of compatible shapes to interact automatically.

In [43]:
x = torch.tensor([[1,2,3], [4,5,6]])

y = torch.tensor([10,20,30])

# x and y are different in shape

# Still the following operation happens as y is broadcast up into the shape of x
z = x + y

print(z)

tensor([[11, 22, 33],
        [14, 25, 36]])


PyTorch conceptually expands y across the rows without physically duplicating the data.

Broadcasting makes code concise and efficient.

### NumPy ↔ PyTorch Interoperability

`torch.from_numpy(numpy_ndarray)` and `tensor.numpy()`.

This interoperability is useful because many scientific Python libraries use NumPy arrays.

In [35]:
import numpy as np

a = [1, 2, 3]
print("Type of 'a':", type(a))

tensor = torch.tensor(a)
print("\nType of 'tensor': ", type(tensor))

to_ndarray = tensor.numpy()
print("\nType of 'to_ndarray':", type(to_ndarray))

back_to_tensor = torch.from_numpy(to_ndarray)
print("\nType of 'back_to_tensor':", type(back_to_tensor))

Type of 'a': <class 'list'>

Type of 'tensor':  <class 'torch.Tensor'>

Type of 'to_ndarray': <class 'numpy.ndarray'>

Type of 'back_to_tensor': <class 'torch.Tensor'>


### CPU vs GPU

To move a tensor to GPU

In [44]:
device = "cuda" if torch.cuda.is_available() else "cpu"

x = x.to(device)

To move it back to CPU

In [45]:
x = x.cpu()

### Mental Model

Think of tensors as containers for multidimensional numerical data.

Everything in PyTorch revolves around tensors. An input image is a tensor, model parameters are tensors, an activation function has tensors as both its input and output.

## Summary

- PyTorch is a deep learning framework built around tensors.
- A tensor generalizes scalars, vectors, matrices, and higher-dimensional arrays.
- You can create tensors from data or using factory functions like `zeros`, `ones`, `eye`, `arange`, `linspace`, `rand`, and `randn`.
- Important tensor attributes include:
  - shape,
  - ndim,
  - dtype,
  - device.
- PyTorch supports indexing, slicing, reshaping, broadcasting, and vectorized arithmetic.
- Matrix multiplication uses `@` or `torch.matmul`, while `*` performs element-wise multiplication.
- PyTorch integrates naturally with NumPy and supports GPU acceleration.

## What ChatGPT Expected Me to Learn from this Project

The purpose of the Tensor Playground was to build fluency.

You should now be able to:

- think in terms of tensor shapes,
- recognize broadcasting opportunities,
- distinguish element-wise and matrix operations,
- understand that everything in a neural network—inputs, parameters, activations, losses, and gradients—is represented as tensors.