# Project 6 — Forward Propagation from Scratch

## Project Description

**Objective**: Implement the complete forward pass of a multi-layer neural network using NumPy.

Requirements:

1. Create a network with:
   - 3 input features,
   - 4 hidden neurons,
   - 2 output neurons.
1. Store weights and biases as NumPy arrays.
1. Implement the forward propagation equations using only vectorized operations (no explicit Python loops over neurons).
1. Implement at least two activation functions (e.g., ReLU and sigmoid) and compare their outputs for the same inputs.
1. Extend the implementation to process a batch of multiple input samples simultaneously.

The emphasis is on writing clean, matrix-based code that mirrors how professional deep learning libraries perform forward propagation.

## My Solution

In [1]:
from pprint import pprint

import numpy as np
import numpy.typing as npt

In [4]:
class NeuralNetwork:
    def __print_on_verbose(self, text):
        if not self.verbose:
            return
        pprint(text)

    def __init__(self, n_neurons_per_layer: tuple[int, ...], verbose : bool = False):
        # I am numbering layers from 0
        self.n_neurons_per_layer = n_neurons_per_layer
        self.verbose = verbose

        self.n_layers = len(n_neurons_per_layer)

        self.__print_on_verbose(f"Initializing a Fully-Connected {len(n_neurons_per_layer)}-Layer Neural Network.")

        # Bias Augmented Weights per Layer starting from Layer 1 (First Hidden Layer)
        self.layer_weights = []
        rng = np.random.default_rng()

        for layer_number, n_neurons in enumerate(n_neurons_per_layer):
            if layer_number == 0:
                print("\n\n")
                self.__print_on_verbose(f"Input Layer (Layer {layer_number}): {n_neurons} Neuron(s).")
            elif layer_number == self.n_layers - 1:
                print("\n\n")
                self.__print_on_verbose(f"Ouput Layer (Layer {layer_number}): {n_neurons} Neuron(s).")
            else:
                print("\n\n")
                self.__print_on_verbose(f"Layer {layer_number}: {n_neurons} Neuron(s).")

            if layer_number == 0:
                self.layer_weights.append(None) # Just a placeholder
            else:
                w = rng.standard_normal((n_neurons, n_neurons_per_layer[layer_number - 1] + 1))
                self.layer_weights.append(w)
                self.__print_on_verbose("Weights (with Bias in Last Column):")
                self.__print_on_verbose(w)

        print("\n\n")
        self.__print_on_verbose("Neural Network Initialized.")


    def predict_on_input(self, x : npt.NDArray[np.number]):
        """Processes the input and start forward propagation.

        Args:
            x: A 2D NumPy Array of shape (number_of_samples, number_of_features). 

        Returns:
            TODO

        Raises:
            TODO
        """
        if not isinstance(x, np.ndarray):
            raise TypeError(f"Expected np.ndarray, got {type(x).__name__}")
    
        if x.ndim != 2 or x.shape[1] != self.n_neurons_per_layer[0]:
            raise ValueError(f"Expected shape ({self.n_neurons_per_layer[0]}, 1), but got shape {x.shape}")
        
        self.current_example = x.T # Sample in Columns

        self.__forward_layer(layer_number = self.n_layers - 1)

    def __leaky_relu_activation(self, x: np.ndarray, alpha: float = 0.01):
        return np.where(x > 0, x, alpha * x)

    def __sigmoid_activation(self, x: np.ndarray):
        return 1.0 / (1.0 + np.exp(-np.clip(x, -500, 500)))

    def __forward_layer(self, layer_number):
        if layer_number == 0:
            return self.current_example

        W = self.layer_weights[layer_number]
        last_layer_activation = self.__forward_layer(layer_number - 1)


        weighted_sum = W @ np.vstack([last_layer_activation, np.ones(last_layer_activation.shape[1])])

        activation = self.__sigmoid_activation(weighted_sum) if layer_number == self.n_layers -1 else self.__leaky_relu_activation(weighted_sum)

        if layer_number == self.n_layers - 1:
            print("\n\n")
            self.__print_on_verbose("Output Layer")
        else:
            print("\n\n")
            self.__print_on_verbose(f"Layer {layer_number}")
        self.__print_on_verbose(f"W:")
        self.__print_on_verbose(W)
        self.__print_on_verbose("Activation of Last Layer")
        self.__print_on_verbose(last_layer_activation)
        self.__print_on_verbose("Weighted Sum of this Layer")
        self.__print_on_verbose(weighted_sum)
        self.__print_on_verbose("Activation of this Layer")
        self.__print_on_verbose(activation)

        
        return activation
            
        



In [5]:
my_first_neural_network = NeuralNetwork((3, 4, 2), verbose=True)

'Initializing a Fully-Connected 3-Layer Neural Network.'



'Input Layer (Layer 0): 3 Neuron(s).'



'Layer 1: 4 Neuron(s).'
'Weights (with Bias in Last Column):'
array([[ 0.06570514,  0.42289265, -0.90436444, -1.24145152],
       [-0.6752422 , -0.2696065 , -0.73626028, -0.04070128],
       [ 0.1160743 , -0.10559057, -1.50121061, -1.01561162],
       [-0.69454866,  2.14753793,  0.25928387, -0.49633253]])



'Ouput Layer (Layer 2): 2 Neuron(s).'
'Weights (with Bias in Last Column):'
array([[-0.45552746, -0.8536777 , -0.78255569, -0.92141883, -0.2378139 ],
       [-0.96070585,  0.71707506,  0.68250122, -1.11443456,  0.70509053]])



'Neural Network Initialized.'


In [6]:
my_first_neural_network.predict_on_input(np.array([[4, -1], [2, 3], [0, -5]]).T)




'Layer 1'
'W:'
array([[ 0.06570514,  0.42289265, -0.90436444, -1.24145152],
       [-0.6752422 , -0.2696065 , -0.73626028, -0.04070128],
       [ 0.1160743 , -0.10559057, -1.50121061, -1.01561162],
       [-0.69454866,  2.14753793,  0.25928387, -0.49633253]])
'Activation of Last Layer'
array([[ 4, -1],
       [ 2,  3],
       [ 0, -5]])
'Weighted Sum of this Layer'
array([[-0.13284567,  4.48334348],
       [-3.28088309,  3.50702284],
       [-0.76249556,  6.0575954 ],
       [ 1.0205487 ,  5.34441055]])
'Activation of this Layer'
array([[-1.32845672e-03,  4.48334348e+00],
       [-3.28088309e-02,  3.50702284e+00],
       [-7.62495562e-03,  6.05759540e+00],
       [ 1.02054870e+00,  5.34441055e+00]])



'Output Layer'
'W:'
array([[-0.45552746, -0.8536777 , -0.78255569, -0.92141883, -0.2378139 ],
       [-0.96070585,  0.71707506,  0.68250122, -1.11443456,  0.70509053]])
'Activation of Last Layer'
array([[-1.32845672e-03,  4.48334348e+00],
       [-3.28088309e-02,  3.50702284e+00],
   

## What ChatGPT Expected Me to Learn from this Project

The project was about `developing a matrix mindset`.

Instead of thinking,

> "One neuron computes one output,"

you should now think,

> "An entire layer computes one matrix operation."

That shift is fundamental to understanding professional deep learning code.